---
title: "R Notebook"
output: html_notebook
---

```{r}
library("ImbCoL")
library("stringr")
library("dplyr")
library(caret)
```

```{r}
#Path to datasets dir:
dir_path = "../../data/5-fold/"

```

```{r}
ds_names <- list("D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "D11", "D12", "D13", "D14", "D15", "D16", "D17", "D18", "D19", "D20", "D21", "D22", "D23", "D24", "D25", "D26", "D27", "D28", "D29", "D30", "D31", "D32", "D33", "D34", "D35", "D36", "D37", "D38", "D39", "D40", "D41", "D42", "D43", "D44", "D45", "D46", "D47", "D48", "D49", "D50", "D51", "D52", "D53", "D54", "D55", "D56", "D57", "D58", "D59", "D60", "D61", "D62", "D63", "D64", "D65", "D66", "D67", "D68", "D69", "D70", "D71", "D72", "D73", "D74", "D75", "D76", "D77", "D78", "D79", "D80", "D81", "D82", "D83", "D84", "D85", "D86", "D87", "D88", "D89", "D90", "D91", "D92", "D93", "D94", "D95", "D96", "D97", "D98", "D99", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D108", "D109", "D110", "D111", "D112", "D113", "D114", "D115", "D116", "D117", "D118", "D119", "D120", "D121", "D122", "D123", "D124", "D125", "D126", "D127", "D128", "D129", "D130", "D131", "D132", "D133", "D134", "D135", "D136", "D137", "D138", "D139", "D140", "D141", "D142", "D143", "D144", "D145", "D146", "D147", "D148", "D149", "D150", "D151", "D152", "D153", "D154", "D155", "D156", "D157", "D158", "D159", "D160", "D161", "D162", "D163", "D164", "D165", "D166", "D167", "D168", "D169", "D170", "D171", "D172", "D173", "D174", "D175", "D176", "D177", "D178", "D179", "D180", "D181", "D182", "D183", "D184", "D185", "D186", "D187", "D188", "D189", "D190", "D191", "D192", "D193", "D194", "D195", "D196", "D197", "D198", "D199", "D200", "D201", "D202", "D203", "D204", "D205", "D206", "D207", "D208", "D209", "D210", "D211", "D212", "D213", "D214", "D215", "D216", "D217", "D218", "D219", "D220", "D221", "D222", "D223", "D224", "D225", "D226", "D227", "D228", "D229", "D230", "D231", "D232", "D233", "D234", "D235", "D236", "D237", "D238", "D239", "D240", "D241", "D242", "D243", "D244", "D245", "D246", "D247", "D248", "D249", "D250", "D251", "D252", "D253", "D254", "D255", "D256", "D257", "D258", "D259", "D260", "D261", "D262", "D263", "D264", "D265", "D266", "D267", "D268", "D269", "D270", "D271", "D272", "D273", "D274", "D275", "D276", "D277", "D278", "D279", "D280", "D281", "D282", "D283", "D284", "D285", "D286", "D287", "D288", "D289", "D290", "D291", "D292", "D293", "D294", "D295", "D296", "D297", "D298", "D299", "D300")
```

```{r}
#path_to_csv_tra <- paste(dir_path,ds_names[44], "/", str_sub(ds_names[44],1,-5), "1tra.csv", sep="")
#path_to_csv_tst <- paste(dir_path,ds_names[44], "/", str_sub(ds_names[44],1,-5), "1tst.csv", sep="")
```

```{r}
## Read both CSVs and concatenate them:
# print(path_to_csv_tra)
# tra = read.csv(path_to_csv_tra)
# tst = read.csv(path_to_csv_tst)
# ds = rbind(tra,tst)
```

```{r}
# check_and_encode <- function(a_ds){
#     if (any(grepl("character", sapply(a_ds, class), fixed=TRUE)))
#     {
#         #define one-hot encoding function
#         dummy <- dummyVars(" ~ .", data=a_ds)
#         #perform one-hot encoding on data.frame and return the resulting data.frame
#         return(data.frame(predict(dummy, newdata=a_ds)))
#     } else {
#         return(a_ds)
#     }
# }        
```

```{r}
ds_names[1]
```

```{r}
paste(dir_path,ds_names[1],"-fold1-train.csv", sep="")
```

Calculating ImbCoL's complexity metafeatures:

```{r}
results_df = data.frame()
for (name in ds_names)
{
    cat("Calculating metafeatures for dataset", name)
    path_to_csv_tra <- paste(dir_path,name,"-fold1-train.csv", sep="")
    path_to_csv_tst <- paste(dir_path,name,"-fold1-test.csv", sep="")
    # Read both CSVs and concatenate them:
    tra = read.csv(path_to_csv_tra)
    tst = read.csv(path_to_csv_tst)
    ds = rbind(tra,tst)
    # Trimming strings
    ds = ds %>% 
        mutate(across(where(is.character), str_trim))
    # One hot encoding (when needed):
    ds = check_and_encode(ds)
    # Calculate metafeatures using ImbCoL:
    result = ImbCoL::complexity(ds[,1:ncol(ds)-1], ds[,ncol(ds)])
    result_df = t(data.frame(result))
    ds_name = c(name)
    result_df = cbind(ds_name, result_df)
    results_df = rbind(results_df, result_df)
}

write.csv(results_df, "/Users/lucasamorim/Dropbox/Doutorado/Pesquisa/Dynamic_selec_scaling_techniques/imbcol_complexity.csv", row.names = FALSE
```

```{r}
#write.csv(results_df, "./imbcol_meta_features.csv", row.names = FALSE)

```

